name: sparrow_image_cropper
description: A Flutter plugin for Android and iOS supports cropping images
version: 0.0.2
homepage: https://github.com/hanguangbaihuo/sparrow_image_cropper

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: '>=1.12.13+hotfix.5'

flutter:
  plugin:
    platforms:
      android:
        package: vn.hunghd.flutter.plugins.sparrowimagecropper
        pluginClass: ImageCropperPlugin
      ios:
        pluginClass: FLTImageCropperPlugin

dependencies:
  flutter:
    sdk: flutter